version: '3.5'
services:
  react-app:
    command: yarn build
  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    tty: true
    links:
      - react-app
    ports:
      - "80:80"
    volumes:
      - ./build:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
