# docker-compose.yml
version: '3.5'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/app/src
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./src:/usr/app/src
    command: ["npm", "test"]